query GetMyRecipes($user_id: uuid!) {
  recipes(where: { user_id: { _eq: $user_id } }) {
    id
    title
    description
    prep_time_minutes
    created_at
    category {
      name
    }
    recipe_images(where: { is_featured: { _eq: true } }, limit: 1) {
      url
    }
    recipe_ingredients {
      id
      name
      quantity
    }
    recipe_steps(order_by: { step_number: asc }) {
      id
      step_number
      description
    }
    user_id
  }
}
