query GetMyRecipes($user_id: uuid!) {
  recipes(where: { user_id: { _eq: $user_id } }) {
    id
    title
    description
    prep_time_minutes
    created_at
    category {
      name
    }
    recipe_images {
      id
      url
      is_featured
    }
    recipe_ingredients {
      id
      name
      quantity
    }
    recipe_steps(order_by: { step_number: asc }) {
      id
      step_number
      description
    }
    user_id
    recipe_likes_aggregate {
      aggregate {
        count
      }
    }
    recipe_comments_aggregate {
      aggregate {
        count
      }
    }
    recipe_ratings_aggregate {
      aggregate {
        count
        avg {
          rating
        }
      }
    }
  }
}
