query GetAllRecipes {
  recipes {
    id
    title
    description
    prep_time_minutes
    created_at
    user_id
    category {
      id
      name
    }
    recipe_images(where: { is_featured: { _eq: true } }, limit: 1) {
      url
    }
    recipe_ingredients {
      id
      name
      quantity
    }
    recipe_steps(order_by: { step_number: asc }) {
      id
      step_number
      description
    }
    user {
      username
    }
    recipe_likes_aggregate {
      aggregate {
        count
      }
    }
    recipe_comments_aggregate {
      aggregate {
        count
      }
    }
    recipe_ratings_aggregate {
      aggregate {
        count
        avg {
          rating
        }
      }
    }
  }
}
