query GetRecipeById($id: uuid!) {
  recipes_by_pk(id: $id) {
    id
    title
    description
    prep_time_minutes
    created_at
    updated_at
    user_id
    category {
      name
    }
    user {
      id
      username
    }
    recipe_images {
      id
      url
      is_featured
    }
    recipe_ingredients {
      id
      name
      quantity
    }
    recipe_steps(order_by: { step_number: asc }) {
      id
      step_number
      description
    }
    recipe_likes_aggregate {
      aggregate {
        count
      }
    }
  }
}
